/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author faheem
 */
public class FrmMenuGrouping extends javax.swing.JInternalFrame {
    private Connection conn;
    private List lstGroupId=new ArrayList();
    
    /**
     * Creates new form FrmMenuGrouping
     */
    public FrmMenuGrouping() {
        initComponents();
    }

    public void setConn(Connection c){
        this.conn=c;
    }
    
    private void udfInitForm(){
        loadGroup("");
    }
    
    private void loadGroup(String s){
        try{
            ResultSet rs=conn.createStatement().executeQuery("select * from m_menu_group "
                    + "where module_name='APOTEK' ");
            cmbGroup.removeAllItems();
            cmbGroup.addItem("<Tambah Grup>");
            lstGroupId.add("");
            while(rs.next()){
                lstGroupId.add(rs.getString("group_id"));
                cmbGroup.addItem(rs.getString("group_id"));
            }
            rs.close();
        }catch(SQLException se){
            JOptionPane.showMessageDialog(this, se.getMessage());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbGroup = new javax.swing.JComboBox();
        txtKeterangan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Grouping Menu");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Keterangan : ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 45, 95, 20);

        jLabel2.setText("Group : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 15, 100, 20);

        cmbGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGroup.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbGroupItemStateChanged(evt);
            }
        });
        cmbGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGroupActionPerformed(evt);
            }
        });
        jPanel1.add(cmbGroup);
        cmbGroup.setBounds(115, 15, 295, 25);
        jPanel1.add(txtKeterangan);
        txtKeterangan.setBounds(115, 45, 340, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(12, 12, 465, 80);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Keterangan Menu", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 95, 465, 215);

        jButton1.setText("Simpan");
        jButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(277, 320, 105, 31);

        jButton2.setText("Batal");
        jButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(385, 320, 85, 31);

        setBounds(0, 0, 493, 386);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        udfInitForm();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        udfSave();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbGroupItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbGroupItemStateChanged
        
    }//GEN-LAST:event_cmbGroupItemStateChanged

    private void cmbGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGroupActionPerformed
        if(lstGroupId.size()==1  ||(cmbGroup.getSelectedIndex()==0 && this.isShowing())){
            String newGroup=JOptionPane.showInputDialog(this, "Grup menu baru :");
            if(newGroup!=null && newGroup.length()>0 && addGroup(newGroup))
                return;
            cmbGroup.addItem(newGroup);
            lstGroupId.add(newGroup);
        }
    }//GEN-LAST:event_cmbGroupActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtKeterangan;
    // End of variables declaration//GEN-END:variables

    private void udfSave() {
        
        
    }

    private boolean addGroup(String newGroup) {
        try {
            ResultSet rs=conn.createStatement(ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_UPDATABLE)
                    .executeQuery("select * from m_menu_group where group_id='"+newGroup+"'");
            if(rs.next()){
                JOptionPane.showMessageDialog(this, "Grup menu '"+newGroup+"' sudah ada!");
                rs.close();
                return false;
            }
            rs.moveToInsertRow();
            rs.updateString("group_id", newGroup);
            rs.updateString("module_name", "APOTEK");
            //rs.updateString("keterangan", newGroup);
            
            rs.insertRow();
            rs.close();
        } catch (SQLException ex) {
            Logger.getLogger(FrmMenuGrouping.class.getName()).log(Level.SEVERE, null, ex);
        }
        return true;
    }
}
